env:
  MINECRAFT_VERSION: 1.20.1
  MOD_VERSION: 1.0-SNAPSHOT

name: Build Mod

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Gradle files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Extract versions from gradle.properties (robust)
        id: extract_versions
        run: |
          MOD_VERSION=$(awk -F= '/^mod_version/ { gsub(/^[ \t]+|[ \t]+$/, "", $2); print $2 }' gradle.properties)

          echo "mod_version=$MOD_VERSION" >> $GITHUB_ENV

      - name: Build the mod
        run: ./gradlew build

      - name: Upload mod jar
        uses: actions/upload-artifact@v4
        with:
          name: silentlibrary-fabric-${{ env.mod_version }}-1.20.1
          path: build/libs/*.jar